#!/usr/bin/env bash
# User overides db and var settings...
# export DXVK_HUD=full
# export GALLIUM_HUD=fps
export GUI_THEME="default"
export BRANCH="master"
export MIRROR="CLOUD"
export DOWNLOAD_STEAM_GRID="1"
export PW_GUI_START="NOTEBOOK"
export DESKTOP_WITH_TIME="posnumber1"
export SORT_WITH_TIME="lastlaunch"
export PW_GPU_USE="NVIDIA GeForce RTX 3070"
export PW_SHORTCUT_MENU="TRUE"
export PW_SHORTCUT_DESKTOP="FALSE"
export PW_SHORTCUT_STEAM="FALSE"
