version = 1

[global]
dll = "/home/xiii/.local/share/Steam/steamapps/common/Lossless Scaling/Lossless.dll"

[[game]]
exe = "2x"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "3x"
multiplier = 3
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "4x"
multiplier = 4
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "5x"
multiplier = 5
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "6x"
multiplier = 6
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"

[[game]]
exe = "Global"
multiplier = 2
flow_scale = 1.0
performance_mode = false
hdr_mode = false
experimental_present_mode = "fifo"
